create table products(
    id bigint generated by default as identity,
    name varchar(100) not null,
    description varchar(250) not null,
    price decimal(19,2) not null,
    quantity_in_stock int not null,
    active boolean not null default true,
    primary key (id)
);