create table users (
    id   bigint generated by default as identity ,
    login varchar(100) not null unique,
    password varchar(255) not null,
    role varchar(20) not null,
    primary key (id)
);