create table sales (
    id bigint generated by default as identity,
    sale_date timestamp not null default now(),
    total_value decimal(19, 2) not null,
    primary key (id)
);

create table sale_items (
    id bigint generated by default as identity,
    sale_id bigint not null,
    product_id bigint not null,
    quantity int not null,
    price_at_sale decimal(19, 2) not null,
    primary key (id),
    foreign key (sale_id) references sales(id),
    foreign key (product_id) references products(id)
);